### ISSUE TITLE
How does mhints start and does it have a right click/click/double click function for the mouse?

### ISSUE THREAD

**Issue by photkey** [itmitica/slimwin#1]
Don't quite understand how to use mhints, from the screenshot it looks like it should be what I need but I don't know how to start it. also does it support right click/click/double click functionality?

**Comment by itmitica** [comment]
Hi.

Start the script and a new icon will apear in the tray, a white square with the letters AZ in it.

Press Ctrl+; to display the grid. Press Esc to hide the grid. 

Press arrow keys to move the grid around. Press the corresponding two letters for the box where you'd like the mouse cursor to move to.

For mouse actions, I use the built-in Mouse Keys. Press Alt+Shift+Numlock to activate Mouse Keys. Please read the help for Mouse Keys.

Short guide

Press Numlock to enable/disable mouse keys. Press /, *, - on the numeric keyboard block to swith between left, all, right click. Press 5 on the numeric keyboard block to click.
